### ISSUE TITLE
Dreifarbiges Waveshare E-Paper Display

### ISSUE THREAD

**Issue by Alveran81** [jp112sdl/HB-Dis-EP-42BW#2]
Hallo,
ist es möglich auch das dreifarbige E-Paper Display einzubinden? Habe versehentlich das falsche bestellt. Es würde auch reichen wenn rot erstmal nicht verwendet wird. 
Genau gesagt dieses:
https://www.waveshare.com/wiki/4.2inch_e-Paper_Module_(B)
https://eckstein-shop.de/Waveshare-42-inch-400x300-E-Ink-E-Paper-Display-Module-Three-color-Arduino

Welche Library muss dafür geladen werden? Hab schon ewig im Netz dazu gesucht, konnte aber nichts sinnvolles finden.

**Comment by jp112sdl** [comment]
Moin,

ja das geht. Ich hab bei mir auch das 3farbige und nutze nur b/w. 😄 

Libs brauchst du alle, die hier unten aufgeführt sind:
https://github.com/jp112sdl/HB-Dis-EP-42BW#arduino
